source 'https://github.com/CocoaPods/Specs.git'
platform :ios, “8.4”

use_frameworks!
pod 'SwiftValidator', '2.1.1'
xcodeproj ‘../Acquere/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj'